### PR TITLE
Add new commands, 'translate-rel' and 'stretch'

### PR DESCRIPTION
**Pull request by udif**
The 'translate-rel' command simple translate the object by the given x,y,z offset instead of setting an absolute point.
The 'stretch' command is used to translate only some of the points, constrained by a box. This is useful for changing the dimensions of the STL, or parts of it.

### CODE REVIEW

**Comment by hroncok** [comment]
Thanks for your contribution Udi! Unfortunately, I don't have much time for this project lately and I am not sure I'll be able to review this code any time soon.

**Comment by gladk** [comment]
Could you please pull from master to check the PR with github-actions? Thanks

**Comment by udif** [comment]
@gladk , did you refer to me? I just merged the github actions config, and set it to run on all push, not only master (it is passing on my branch).

**Comment by gladk** [comment]
Please resolve consficts. Thanks.

**Comment by udif** [comment]
@gladk can you merge my PR?

**Pull request merged**
