### PR TITLE
make scale_versor available via CLI

### PR DESCRIPTION
**Pull request by daef**
I was missing this feature :)

### CODE REVIEW

**Comment by hroncok** [comment]
Could you please also update the doc? https://github.com/admesh/admesh/blob/master/admesh-doc.txt and https://github.com/admesh/admesh/blob/master/admesh.1

**Comment by daef** [comment]
I really don't know anything about the manpage syntax in the admesh.1 file, but I gave my best to add a nice example to admesh-doc.txt

**Comment by hroncok** [comment]
Thanks a lot for your contribution! I'll do my best to review and test is soon, however I'm swamped by other tasks. Feel free to bump this if not done by the end of the week.

**Comment by daef** [comment]
I hope you had a nice weekend.
I'm not in a hurry, bumping for completeness.

**Comment by hroncok** [comment]
Thanks! DO you need a backport? And a release?

**Comment by daef** [comment]
I can work from source, I don't know which channels would benefit from a release

**Pull request merged**
